### ISSUE TITLE
Bidnamic task part 2

### ISSUE THREAD

**Issue by jakej230196** [jakej230196/bidnamic-python-challenge#2]

**Comment by jakej230196** [comment]
just linking to the parent issue #1

**Comment by jakej230196** [comment]
working on branch https://github.com/jakej230196/bidnamic-python-challenge/tree/part-2

Gitlab has features which lets you create branches from issues & issues automatically close when a mr is approved, on gitlab you need 3rd party apps :(

**Comment by jakej230196** [comment]
Had a go at generating the uuid at the end of the ad group alias but no luck - was hoping it would just be a uuid of something like {campaign_id-searchterms-something} but I'm not about to try every possible combination :) 

I am going to restructure that field to JSON though, as it's obvious that's what it is, but still not sure what some of the fields are. Here's what i have so far:


```
Alias: {
    'Unknownfield': 'Shift',
    'Unknown field': 'Shopping'
    'Region': 'GB',
    'Company' (structure_value): 'venum',
    'Purchase Intent': 'LOW',
    'Search Term': 'monkey-ack-robert-comet',
    'Uuid':  '817ce4882dfc499886ca8670ccd5cbf9'

}
```

**Comment by jakej230196** [comment]
run into this: 

```
sycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
DETAIL:  Token "Shift" is invalid.
CONTEXT:  JSON data, line 1: Shift...


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jake/python/github.com/bidnamic-python-challenge/bidnamic_task/manage.py", line 22, in <module>
    main()
  File "/home/jake/python/github.com/bidnamic-python-challenge/bidnamic_task/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/core/management/base.py", line 90, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 253, in handle
    post_migrate_state = executor.migrate(
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/migrations/executor.py", line 126, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/migrations/executor.py", line 156, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/migrations/executor.py", line 236, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/migrations/migration.py", line 125, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 225, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 618, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 196, in _alter_field
    super()._alter_field(
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 775, in _alter_field
    self.execute(
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 151, in execute
    cursor.execute(sql, params)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jake/.local/share/virtualenvs/bidnamic-python-challenge-h09bK-Ct/lib/python3.9/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: invalid input syntax for type json
DETAIL:  Token "Shift" is invalid.
CONTEXT:  JSON data, line 1: Shift...

```

Spent way too long trying to find out why it was happening, looking at psycog source etc. In the end it was because my migration order was wrong....

**Comment by jakej230196** [comment]
It's working now but it's given me a headache, was expecting it to take 15m and it's been 3 hours. 

Anyway,
this is how the fields looks now:

```
{"region": "GB", "category": "Shopping", "uuid_hex": "817ce4882dfc499886ca8670ccd5cbf9", "search_term": "monkey-ack-robert-comet", "unknown_field": "Shift", "purchase_intent": "LOW", "structure_value": "venum"}
``` 

Not sure if they are the right names or not but it's the best i have atm & will be easier to query

**Comment by jakej230196** [comment]
Will be back on this today, starting with writing serializers for each model then will comment on the next step - will be starting in ~20m

**Comment by jakej230196** [comment]
> Had a go at generating the uuid at the end of the ad group alias but no luck - was hoping it would just be a uuid of something like {campaign_id-searchterms-something} but I'm not about to try every possible combination :)
> 
> I am going to restructure that field to JSON though, as it's obvious that's what it is, but still not sure what some of the fields are. Here's what i have so far:
> 
> ```
> Alias: {
>     'Unknownfield': 'Shift',
>     'Unknown field': 'Shopping'
>     'Region': 'GB',
>     'Company' (structure_value): 'venum',
>     'Purchase Intent': 'LOW',
>     'Search Term': 'monkey-ack-robert-comet',
>     'Uuid':  '817ce4882dfc499886ca8670ccd5cbf9'
> 
> }
> ```
I'm now thinking they should be seperate higher-level fields but i'm going to wait until the end of the task to review everything

**Comment by jakej230196** [comment]
Going to start writing the endpoints now, had a look around and settled on using: https://dynamic-rest.readthedocs.io/en/latest/tutorial.html#introduction because it has simple field filtering and supposedly efficient side-loading for related objects.

**Comment by jakej230196** [comment]
Have a basic api - going to add some filtering etc & work out how to optimize it. It's currently getting all related objects so the query time is ridiculous

**Comment by jakej230196** [comment]
I'm more comfortable with the django rest framework now, still not looked at the optimization. Just going to add some basic views to each model now which will return the first entry and then look at how to apply the query arguments & then look at optimizing

**Comment by jakej230196** [comment]
Have done the filtering for structure_value. Currently looking at how to return data when there's multiple campaign_ids for a structure value, i'm thinking something like this:

{response: 
body: {
campaign_id1: {data},
campaign_id2: {data}
}
}

with nested field containing ordered search term data

**Comment by jakej230196** [comment]
There's the option to group by campaign id when filtering by structure_value, was going to try and make it generic so we could do other grouping but i'd rather finish the basic parts of the task first

**Comment by jakej230196** [comment]
So the query:



GET /api/searchterms/?campaign_structure_value=venum&group_by=campaign&limit=1&order_by=-roas



returns:

```

{
    "1578451881": [
        {
            "search_term_id": 3694268513669316915,
            "date": "2018-12-09",
            "ad_group": 59898740136,
            "campaign": 1578451881,
            "clicks": 1,
            "cost": "0.19",
            "conversion_value": "27.98",
            "conversions": 1,
            "search_term": "venum mma gloves uk",
            "roas": "147.26"
        }
    ],
    "1578451887": [
        {
            "search_term_id": 2852550811457112881,
            "date": "2018-12-01",
            "ad_group": 59898740336,
            "campaign": 1578451887,
            "clicks": 1,
            "cost": "0.06",
            "conversion_value": "27.98",
            "conversions": 1,
            "search_term": "best budget mma glives",
            "roas": "466.33"
        }
    ],
    "1578451884": [
        {
            "search_term_id": 3063982974126603854,
            "date": "2020-05-06",
            "ad_group": 70580080733,
            "campaign": 1578451884,
            "clicks": 1,
            "cost": "0.13",
            "conversion_value": "119.99",
            "conversions": 1,
            "search_term": "venum boxing boots",
            "roas": "923.00"
        }
    ]
}
```
but if you omit the group by argument all you get is:



GET /api/searchterms/?campaign_structure_value=venum&limit=1&order_by=-roas


```

[
    {
        "search_term_id": 3063982974126603854,
        "date": "2020-05-06",
        "ad_group": 70580080733,
        "campaign": 1578451884,
        "clicks": 1,
        "cost": "0.13",
        "conversion_value": "119.99",
        "conversions": 1,
        "search_term": "venum boxing boots",
        "roas": "923.00"
    }
]

```

**Comment by jakej230196** [comment]
Finished the docs for searching for campaign structure values, will go write the code to search by adgroup alias.

**Comment by jakej230196** [comment]
I have the adgroup alias search working now, going to add some functions to do partial searches

**Comment by jakej230196** [comment]
I think i'll close this issue as the very basic functionality to search by the adgroup alias is there, i.e:
```
http://localhost:8000/api/searchterms/?adgroup_alias=Shift%20-%20Shopping%20-%20GB%20-%20venum%20-%20LOW%20-%20monkey-ack-robert-comet%20-%20817ce4882dfc499886ca8670ccd5cbf9&limit=1

```
returns:

```


HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "search_term_id": 7929458609716478631,
        "date": "2019-05-22",
        "ad_group": 66372665454,
        "campaign": 1578451881,
        "clicks": 2,
        "cost": "0.28",
        "conversion_value": "0.00",
        "conversions": 0,
        "search_term": "venum spats",
        "roas": "0.00"
    }
]


```

**Comment by jakej230196** [comment]
Will add additional functionality in another issue, but i think this issue can be closed as it's the MVP
